# To debug:
#   griffe dump gsp -o/dev/null -LDEBUG
#   mkdocs -v
# See also https://github.com/mkdocstrings/mkdocstrings/issues/451
site_name: Graphic Server Protocol 
use_directory_urls: false
repo_url: https://github.com/rougier/gsp-matplotlib
remote_name: origin # For mkdocs gh-deploy
docs_dir: 'docs'

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 


plugins:
#  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: no
            merge_init_into_class: no
            show_submodules: yes
            show_root_heading: yes
            show_source: no
            show_bases: no
            show_root_full_path: no
            show_signature_annotations: no
            separate_signature: yes

nav:
 - Overview:
   - index.md
   - protocol.md
   - Implementations:
     - matplotlib.md
 - API:
   - Core:
     - api/core/data.md
     - api/core/buffer.md
     - api/core/canvas.md
     - api/core/viewport.md
     - api/core/types.md
   - Visual:
      - api/visual/pixels.md
      - api/visual/points.md
      - api/visual/markers.md
      - api/visual/segments.md
      - api/visual/mesh.md
   - Transform:
     - api/transform/transform.md
     - api/transform/screen.md
     - api/transform/colormap.md
     - api/transform/light.md
     - api/transform/measure.md
 - Examples:
   - examples/quickstart.md
